### ISSUE TITLE
Nova Repeater field

### ISSUE THREAD

**Issue by DenisYakimchuk** [spatie/nova-translatable#105]
Looks like it doesn't work for a Repeatable field:

```Laravel\Nova\Fields\Repeater\Repeatable::Laravel\Nova\Fields\Repeater\{closure}(): Argument #1 ($field) must be of type Laravel\Nova\Fields\Field, Spatie\NovaTranslatable\Translatable given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php on line 240 {"userId":1,"exception":"[object] (TypeError(code: 0): Laravel\\Nova\\Fields\\Repeater\\Repeatable::Laravel\\Nova\\Fields\\Repeater\\{closure}(): Argument #1 ($field) must be of type Laravel\\Nova\\Fields\\Field, Spatie\\NovaTranslatable\\Translatable given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php on line 240 at /var/www/html/vendor/laravel/nova/src/Fields/Repeater/Repeatable.php:99)```

**Comment by hagealex** [comment]
Hello! 

I get the same or at least a similar error:

```
local.ERROR: Spatie\NovaTranslatable\Translatable::Spatie\NovaTranslatable\{closure}(): Argument #2 ($model) must be of type Illuminate\Database\Eloquent\Model, null given
```

This is how I set up the repeatable:

```
Repeater::make('FAQs', 'faqs')
                ->repeatables([
                    CategoryFaq::make(),
                ])->asJson(),
```

This is the fields definition in my `CategoryFaq` Nova model:

```
  return [
            ID::make()->sortable(),
            Translatable::make([
                Text::make('Frage', 'question'),
                Textarea::make('Antwort', 'answer')
            ]),
        ];
```

In the Laravel modal I also added the  `HasTranslations` trait and set up the `$translatable`.


Do I have a missconfiguation or is it a problem with the package?

Kind regards
