### ISSUE TITLE
work with custom text editor field, nova

### ISSUE THREAD

**Issue by Enmaboya** [spatie/nova-translatable#15]
why the field does not work with CKEditor4 Field or Nova TinyMCE ?
just empty field

        Translatable::make([
                NovaTinyMCE::make('translatable_value'),
        ]),

but if i write

        Translatable::make([
                NovaTinyMCE::make('translatable_value_### fr'),
        ]),

The field will appear, but I will not be able to make changes, because I do not have such a field

**Comment by rubenvanassche** [comment]
Hi Enmaboya,

I've looked at your problem, it seems like an issue with TinyMCE which we don't use here at Spatie. The default Nova editor Trix is working fine. Feel free to send in an PR with changes which will solve the problem.
