### ISSUE TITLE
Why not tab

### ISSUE THREAD

**Issue by taliptako** [spatie/nova-translatable#23]
Displaying the fields like that when having a lot of languages looking so ugly.
I think Tabs will look better and suits to everyone's project 
[https://github.com/mrmonat/nova-translatable](https://github.com/mrmonat/nova-translatable) like in this package 
But problem with this package is it doesnt allow to use different field types ..

**Comment by freekmurze** [comment]
https://github.com/spatie/nova-translatable/blob/master/README.md#on-customizing-the-ui

**Comment by nielspeen** [comment]
Not exactly what @taliptako is asking for, but our work-around for the time being is to:

Add an array of allowed locales to our config/app.php:
```php
'locale' => 'en',
'locales' => [ 'en', 'zh', 'nl', 'jp' ],
```

Determine relevant languages in the Nova resource: 
(In our case English + the user's own locale if allowed.)

```php
$locales = [ 'en' ];
if(app()->getLocale() != 'en' && in_array(app()->getLocale(), Config::get('app.locales'))) $locales = [app()->getLocale(), 'en'];
```

Limit the Translatable to the determined locales:

```php
return [
    ID::make()->sortable()
        ->hideFromIndex(),

    Translatable::make([
        Text::make('Title')
            ->rules('max:80'),
    ... more fields...
])->locales($locales),
```

Our users see their own language at the top, with the master language (english) below it. All other languages are hidden (and safe!)

The very few users that must access more languages can use a browser add-on to quickly switch locales.
