### ISSUE TITLE
Translatable Field Uniqueness Validation

### ISSUE THREAD

**Issue by bertranddupraz** [spatie/nova-translatable#25]
TL-DR : I want to check uniqueness by locale for translatable fields but don't find how

I try to ensure that a user can only set unique value for a translatable field. 

I've set up the field like this
```php
Translatable::make([
    Text::make('name')
        ->rules('required', 'string', 'unique:sports,name')
]),
```

Let's assume a simple Sport resource with only a translatable name.  I create a first sport with those translations : 
- Name (fr) : Football
- Name (en) : Football

and then another one with the followings : 

- Name (fr) : Football
- Name (en) : Soccer

This only checks that the whole json is unique so the previous example the validation passes. What I want to accomplish is to check that the uniqueness is checked at the translation level so the validation should fail (because Football is already used in the first fr locale in the example). Is their a way to achieve that ?

**Comment by gldrenthe89** [comment]
Please consider reopening this

**Comment by jorenvh** [comment]
@bertranddupraz @gldrenthe89 as mentioned in the laravel-translatable docs you should use https://github.com/codezero-be/laravel-unique-translation to accomplish this.

> if you want to validate an attribute for uniqueness before saving/updating the db, you might want to have a look at laravel-unique-translation which is made specifically for laravel-translatable.

**Comment by mcanvar** [comment]
For those folks who doesn't want to use a package for this, you may achieve something similar like this:

```
Text::make('Alternative Text', 'alt')
                ->rules('required', function($attribute, $value, $fail) {
                    if (\App\Media::where('alt->en', $value)->count() > 0) {
                        return $fail('The value "' . $value .'" has already taken!');
                    }
                })->translatable(),
```

**Comment by AhmedKamal148** [comment]
You Can Do This 
                'name_en' => ['required', Rule::unique('table_name', 'name->' . 'en')],
                'name_ar' => ['required', Rule::unique('table_name', 'name->' . 'ar')],
