### ISSUE TITLE
It is possible to make tabs by yourself?

### ISSUE THREAD

**Issue by Ragash** [spatie/nova-translatable#30]
i was wondering if could be possible extending the package or if there is a know workaround to see the fields on tabs?

the package is awesome, but aving redundant fields just hurts eyes <3

**Comment by itsdanreed** [comment]
I completely agree. It's overwhelming and not an optimal user experience.

**Comment by chrismackie28** [comment]
You could use panels and define which locale to use in each with `->locales(['en'])`
