### ISSUE TITLE
Can't translate "We offer Aluminium Fence" in de

### ISSUE THREAD

**Issue by ceejay123** [spatie/nova-translatable#39]
I have a nova field description and I used this package to translate the description to my supported locale in my app then when I type this sentence "We offer Aluminium Fence" and then create it, the sentence can't translate into de

**Comment by MilesWuCode** [comment]
me too, when creating

**Comment by ceejay123** [comment]
> me too, when creating

Do you know how to fix it ?

**Comment by ceejay123** [comment]
I just fix the problem , you just put the base language to en
