### ISSUE TITLE
Can not work with nova KeyValue Field

### ISSUE THREAD

**Issue by zmj888** [spatie/nova-translatable#44]
When I use nova KeyValue Field with nova-translatable, the key and values will be broken
![WechatIMG182](https://user-images.githubusercontent.com/11935531/90033011-8f710800-dcf1-11ea-9e33-ce714c886a21.jpeg)

**Comment by zmj888** [comment]
Solved it by set  a Mutator.

**Comment by Gberzi01** [comment]
In case someone else comes upon this thread, the mutator that worked for me was
`public function setXAttribute($value): void
    {
        $this->attributes['X'] = json_decode($value, true);
    }`
