### ISSUE TITLE
No matching package found

### ISSUE THREAD

**Issue by indigoram89** [spatie/nova-translatable#51]
When I do composer update then I get the next error:

<img width="1038" alt="Screenshot 2020-09-29 at 16 13 53" src="https://user-images.githubusercontent.com/10687211/94563109-e4031f00-026e-11eb-9784-0d4b9be04d15.png">

**Comment by indigoram89** [comment]
I have the next requirements in the composer.json file:

<img width="369" alt="Screenshot 2020-09-29 at 16 14 53" src="https://user-images.githubusercontent.com/10687211/94563177-fa10df80-026e-11eb-9f19-d640299f7321.png">

Laravel Nova installed how It described in the documentation and works fine before updating to laravel 8.

**Comment by tainmar** [comment]
See https://github.com/spatie/nova-translatable/pull/52 @indigoram89
