### ISSUE TITLE
Adding Translatable to new Panel doesn't work

### ISSUE THREAD

**Issue by Joorren** [spatie/nova-translatable#87]
# Issue
When adding Translatable fields to a new Panel, the Translatable fields just get added to the main Panel.

# How To Reproduce
1. Add a new Panel to the resource fields
2. Add a Translatable field to the new Panel

# Versions
* PHP: 8.2
* Laravel: 10.1.5
* Nova: 4.22.1
* Nova-Translatable: 3.1.2

# Example
I created an example that also includes a new Panel with a regular Nova field, to show that the issue isn't related to the Panel itself. The new Panel with a Nova field does get added. The new Panel with a Translatable field does not get added, the Translatable field gets added to the main Panel instead.
## Code
```php
...
    public function fields(NovaRequest $request): array
    {
        return [
            ID::make()->sortable(),

            // Working new Panel with Nova fields
            new Panel('External Fields', [

                Text::make('External Description')
                    ->sortable()
                    ->readonly(),

                Text::make('External Type')
                    ->sortable()
                    ->readonly(),
            ]),

            // Broken new Panel with Translatable fields
            new Panel('Candidate Translations', [
                Translatable::make([
                    Text::make('Candidate Description')
                        ->sortable()
                        ->hideFromIndex(),
                ]),

                Translatable::make([
                    Text::make('Candidate Type')
                        ->sortable()
                        ->hideFromIndex(),
                ]),
            ]),
        ];
    }
...
```
## Result
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/22602428/223400843-2cac5ab9-e473-4fb6-861a-d43047737fc7.png">

**Comment by Joorren** [comment]
Changes made in https://github.com/spatie/nova-translatable/pull/77 don't seem to do the trick anymore.

**Comment by Joorren** [comment]
Combining a Nova field and a Translatable field into the same new Panel results in the Nova field showing in the new Panel and the Translatable field showing in the main Panel.

**Comment by xPhantomNL** [comment]
Running into this issue as well, any update on this?

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by ozanhazer** [comment]
I think the filter @xPhantomNL mentioned not only filters but also merges the field data to the original fields wrapped by `Translatable` and thus the panel information is copied over to the original fields and removed from `Translatable`.

Removing lines 192 & 193, as in below, fixes the issue but I'm not sure how to patch this without breaking backward compatibility.

```php
class Translatable extends MergeValue
{
    // ....
    protected function createTranslatedField(Field $originalField, string $locale): Field
    {
        // ....
        $translatedField
            ->resolveUsing(function ($value, Model $model) use ($translatedField, $locale, $originalAttribute) {
                $translatedField->attribute = 'translations_'.$originalAttribute.'_'.$locale;
//                $translatedField->panel = $this->panel;
//                $translatedField->assignedPanel = $this->assignedPanel;

                return $model->translations[$originalAttribute][$locale] ?? '';
            });

```

**Comment by marijoo** [comment]
This is still a problem.

**Comment by marijoo** [comment]
This is still a problem, I opened a PR #99
