### ISSUE TITLE
Maintenance of Nova 3 support

### ISSUE THREAD

**Issue by bram-pkg** [spatie/nova-translatable#88]
Hello Freek,

I would like to ask for permission to maintain a Nova 3 compatible fork of this repo over at https://github.com/carandclassic/laravel-nova-translatable

Of course 99% of the repository would stay the same and Spatie would be credited.

**Comment by freekmurze** [comment]
Hi Bram, 

instead of forking, I could also give you write access to ours so you can help maintain it.

If you want to do this, let me know! 

If you want to keep your own fork, that's of course fine too.

**Comment by bram-pkg** [comment]
It would be easiest to maintain a separate branch and major version for Nova 3. Removing Nova 3 support on a minor/patch release was not the best way to go about it, I don't think :sweat_smile: 

If you could give me write access to a Nova 3 branch, that would be ideal.

**Comment by freekmurze** [comment]
I've given you write access to the repo, so you can make the necessary changes. 

Before making a first release, give me a heads up so I can do a final check on things.

Feel free to ask any questions you might have.

Have fun working on this package.

**Comment by bram-pkg** [comment]
@freekmurze what is the best way to have a quick conversation regarding v3?

Would it be possible to release a 4.x that supports Nova 4 and keep the 3.x around with Nova 3 support?

What do you suggest is the best way to maintain these two versions in parallel?

**Comment by freekmurze** [comment]
It seems like it's currently a bit of mess as we tagged 3.0.5 with only support for Nova 4, and dropped support for Nova 3 there.

Here's what I think we should do:

- create a new 4.x major like with only support for Nova 4 (like you suggest)
- make a new release in the 3.x range with only support for Nova 3, create a v3 branch to work on for the v3 release
- add a note in the readme saying that Nova 3 users should use v3, Nova 4 user should use v4

Does that make it clear?

**Comment by bram-pkg** [comment]
That looks good to me. Could you tag a 4.x release? It would be good going forward to keep this package version in sync with Nova's, I think.
I've already made a `3.x` branch that the `composer.json` can refer to for `3.x-dev`.

**Comment by freekmurze** [comment]
@bram-pkg released 4.0.0 👍

**Comment by bram-pkg** [comment]
Awesome. Let's tag a release on the 3.x branch then.

**Comment by bram-pkg** [comment]
I've release `3.2.0` which only supports Nova 3, and provided a command in the release notes for upgrading to `^4.0` that you released earlier.
